#!/usr/bin/env node
// Keep alternate-language typography identical to its standalone edition.
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { LANGS, readSource } = require('./text_sources');
const HELPERS = [
  'hasCjk', 'britishDashes', 'polishChoiceText', 'smartenText', 'smartenHtml',
  'isChineseSpeechAside', 'wrapChineseSpeechAsides', 'isEnglishSpeechAside',
  'formatEnglishSpeechAside', 'isRomanceSpeechAside', 'formatRomanceSpeechAside',
  'wrapEnglishSpeechAsides', 'polishStoryHtml', 'normaliseLegacyHtml',
  'ensureStoryBlock', 'balanceLegacyHtml',
];
function renderer(source) {
  const helpers = HELPERS.map(name => source.functions.find(f => f.name === name))
    .filter(Boolean).map(f => source.script.slice(f.start, f.end)).join('\n\n');
  return `/* BEGIN ALTERNATE_RENDERER — generated by maintenance/build_bilingual_renderer.js */
var alternateRenderer = (function () {
${helpers}
  return {
    choice: polishChoiceText,
    story: function (value) {
      return balanceLegacyHtml(polishStoryHtml(ensureStoryBlock(normaliseLegacyHtml(value))));
    }
  };
})();
/* END ALTERNATE_RENDERER */`;
}
function main() {
  const pending = LANGS.slice(1).map(lang => {
    const mono = readSource(lang), bilingual = readSource(lang, true), block = renderer(mono);
    const pattern = /\/\* BEGIN ALTERNATE_RENDERER[^]*?\/\* END ALTERNATE_RENDERER \*\//;
    const output = pattern.test(bilingual.html)
      ? bilingual.html.replace(pattern, () => block)
      : bilingual.html.replace('var alternateLanguageName =', () => block + '\n\nvar alternateLanguageName =');
    assert.notEqual(output, '', 'Missing bilingual source');
    return { file: bilingual.file, current: bilingual.html, output };
  });
  if (process.argv.includes('--check')) {
    assert(pending.every(p => p.current === p.output), 'Stale alternate renderer; run node maintenance/build_bilingual_renderer.js');
    console.log('Bilingual alternate renderers match all four standalone editions (read-only).');
  } else {
    for (const p of pending) if (p.current !== p.output) fs.writeFileSync(p.file, p.output);
    console.log('Synchronized all four bilingual alternate renderers.');
  }
}
if (require.main === module) main();
module.exports = { renderer };
