const { runRoute } = require("./verify_routes.js");

const baseStart = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
];

const earlyBushHouseBase = baseStart.concat([
  "Tuesday.",
  "On with the story!",
  "Buy something.",
  "An overpriced bottle of water (£3)",
  "Back to store.",
  "Just head for the theatre.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Talk about trains?",
  "Gosh!",
  "Carry on chatting.",
  "The waiter takes away your plates.",
  "Cheers.",
  "No, let’s go straight to the coffees; the sweets are always a waste of money.",
  "An espresso (£1.50 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Try to stop her?",
  "You take your seats in the auditorium.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Just carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Tell her you need to go?",
  "You go out onto the balcony.",
  "You carry on chatting.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Lean closer to her?",
  "Carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Meet Molly at the stage door and maybe have a drink somewhere else?",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "What a good idea.",
  "You drink your coffees.",
  "She nestles closer to you.",
  "You are sitting next to Diane.",
  "You chat away.",
  "“You’re joking! I’m enjoying this.”",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "You’re quite happy about that.",
  "Talk about trains.",
  "She marches you forward.",
  "OK.",
  "How?",
  "Find her somewhere to go.",
  "She can’t stand still.",
  "Thank you, she says.",
  "You walk on.",
  "Hurrah!",
  "But you walk on past it.",
  "You hurry along.",
  "You buy the drinks.",
  "You go to the bar.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "Yes, I’ll buy another round of drinks.",
  "It’s your round, but quite a cheap one because of the special offers.",
  "Cheers!",
  "Good idea.",
  "Return to the beer garden.",
  "You drink up.",
  "You get ready to leave.",
  "And head for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Get the taxi?",
  "Find a taxi.",
  "You settle back.",
  "The taxi pulls away onto the main road.",
  "Put your arm round her?",
  "The journey continues.",
  "You’re about halfway home.",
  "Almost home.",
  "The taxi continues to your house.",
  "You get out.",
  "You find the key.",
  "You give her a kiss.",
  "They shake hands.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "He goes upstairs.",
  "What will you do next?",
  "So she says nothing.",
]);

function report(name, route) {
  try {
    const r = runRoute(route);
    const ending = r.text.match(/TRULY, YOU HAVE WON FIRST PRIZE!|YOU HAVE WON [^!]+!|WHICH IS A PRETTY GOOD CONSOLATION PRIZE!/i)?.[0] || "NO END";
    console.log(`OK ${name}: ${ending}`);
    console.log("choices:", r.choices.map((c) => c.text).join(" | "));
    console.log("state:", JSON.stringify({ blad: r.vars.blad, proc: r.vars.proc, inti: r.vars.inti, points: r.vars.points, luckshots: r.vars.luckshots, gopee: r.vars.gopee }));
    console.log(r.text.slice(-700));
  } catch (error) {
    console.log(`FAIL ${name}: ${String(error.message).slice(0, 2500)}`);
  }
}

module.exports = { baseStart, earlyBushHouseBase, report };
