const fs = require("fs");
const vm = require("vm");
const { earlyBushHouseBase } = require("./check_endings.js");

const EN_HTML = "outputs/en/dianedate_en.html";
const CN_HTML = "outputs/cn/dianedate_cn.html";
const ES_HTML = "outputs/es/dianedate_es.html";
const FR_HTML = "outputs/fr/dianedate_fr.html";
const TW_HTML = "outputs/tw/dianedate_tw.html";
// External .txt guides/transcripts were removed; Gallery is the player-facing guide.
const LEGACY_GUIDE_OUTPUTS = [
  "outputs/en/endings",
  "outputs/cn/endings",
  "outputs/es/endings",
  "outputs/fr/endings",
  "outputs/tw/endings",
  "outputs/en/guides",
  "outputs/cn/guides",
  "outputs/es/guides",
  "outputs/fr/guides",
  "outputs/en/dianeguide_en.txt",
  "outputs/cn/dianeguide_cn.txt",
  "outputs/es/dianeguide_es.txt",
  "outputs/fr/dianeguide_fr.txt",
  "outputs/en/hidden_scenes_guide_en.txt",
  "outputs/cn/hidden_scenes_guide_cn.txt",
  "outputs/es/hidden_scenes_guide_es.txt",
  "outputs/fr/hidden_scenes_guide_fr.txt",
];

const common = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
];

const tuesdayShortHouse = common.concat([
  "Tuesday.",
  "On with the story!",
  "Just go there.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Ravioli—you’re trying to save money (£7)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Tiramisu (£5 each)",
  "The sweets are delicious and quickly eaten.",
  "Just an ordinary filter coffee (£1 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Or do you want to play the short version of the game?",
  "Yes, I’ll play the short version.",
  "Let’s see what happens!",
  "You find the key.",
  "You give her a kiss.",
  "You usher Diane in.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "What will you do next?",
  "You move to the lounge.",
  "What will you do next?",
  "So she says nothing.",
]);

const saturdayTheatre = common.concat([
  "Saturday.",
  "On with the story!",
  "Just go there.",
  "Say you wish you were on her side of the table.",
  "OK.",
  "A bottle of Italian Pinot Grigio (£10)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Ask if she wants a pee?",
  "You order two coffees.",
  "You smile at her.",
  "You head into the theatre.",
  "You head into the theatre.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Just carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Just carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Use a luckshot?",
  "You wait for her.",
  "You go out onto the balcony.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Just carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Be a gentleman and ask Diane what she wants to do.",
  "You head for the stagedoor.",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
]);

const saturdayHouse = saturdayTheatre.concat([
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "You say there really isn’t time.",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "What are you going to talk about?",
  "Nothing in particular.",
  "OK.",
  "You hurry up.",
  "Hurrah!",
  "You stop in your tracks.",
  "You walk on.",
  "You hurry along.",
  "You buy the drinks.",
  "You go to the bar.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "No, I’m running out of money.",
  "No, I can’t afford it.",
  "You drink up.",
  "Yes, you’ve plenty of time.",
  "You look for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Get the taxi?",
  "Find a taxi.",
  "You wait.",
  "You carry on waiting.",
  "You are at the front of the queue.",
  "The taxi pulls away onto the main road.",
  "Put your arm round her?",
  "The journey continues.",
  "You’re about halfway home.",
  "Almost home.",
  "The taxi continues to your house.",
  "You get out.",
  "You find the key.",
  "You give her a kiss.",
  "They shake hands.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "He goes upstairs.",
  "What will you do next?",
  "So she says nothing.",
]);

const firstDrink = [
  "Offer her another drink?",
  "You go to the kitchen.",
  "Cheers!",
  "You carry on exploring and talking.",
];

const repeatDrink = [
  "Get her another drink?",
  "You go to the kitchen.",
  "Cheers!",
  "You carry on exploring and talking.",
];

const thursdayFifthBase = common.concat([
  "Thursday.",
  "On with the story!",
  "Just go there.",
  "Say you’ve really been looking forward to seeing each other again.",
  "OK.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Ravioli—you’re trying to save money (£7)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Tiramisu (£5 each)",
  "The sweets are delicious and quickly eaten.",
  "An espresso (£1.50 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Or do you want to play the short version of the game?",
  "Yes, I’ll play the short version.",
  "Let’s see what happens!",
  "You find the key.",
  "You give her a kiss.",
  "You usher Diane in.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "What will you do next?",
  "You move to the lounge.",
  "What will you do next?",
  "So she says nothing.",
]);

const chloeBase = common.concat([
  "Tuesday.",
  "On with the story!",
  "Just go there.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Spaghetti bolognese (£8)",
  "Begin the meal.",
  "You chat about your meal.",
  "You concentrate on your eating.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Tiramisu (£5 each)",
  "The sweets are delicious and quickly eaten.",
  "Just an ordinary filter coffee (£1 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Or do you want to play the short version of the game?",
  "Yes, I’ll play the short version.",
  "Let’s see what happens!",
  "You find the key.",
  "You give her a kiss.",
  "It’s all very civilised.",
]);

const amandaBase = common.concat([
  "Saturday.",
  "On with the story!",
  "Just go there.",
  "Say you love the dress.",
  "OK.",
  "A bottle of Italian Pinot Grigio (£10)",
  "Go on to the food menu.",
  "You don’t really like Italian food, so you order a steak (£14)",
  "Well done.",
  "You take a sip of water.",
  "You chat about your meal.",
  "You carry on chatting.",
  "You carry on chatting.",
  "What will it be?",
  "Ask if she wants a pee?",
  "You order two coffees.",
  "You smile at her.",
  "You head into the theatre.",
  "You head into the theatre.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Just carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Just carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Use a luckshot?",
  "You wait for her.",
  "You go out onto the balcony.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Just carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Be a gentleman and ask Diane what she wants to do.",
  "You head for the stagedoor.",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "You say there really isn’t time.",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "What are you going to talk about?",
  "Nothing in particular.",
  "OK.",
  "You hurry up.",
  "Hurrah!",
  "You stop in your tracks.",
  "You walk on.",
  "You hurry along.",
  "You buy the drinks.",
  "No, I’ll hold onto my luckshots.",
  "You chat together.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "No, I’m running out of money.",
  "No, I can’t afford it.",
  "You drink up.",
  "You get ready to leave.",
  "And head for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Get the taxi?",
  "Find a taxi.",
  "You wait.",
  "You carry on waiting.",
  "You are at the front of the queue.",
  "The taxi pulls away onto the main road.",
  "Put your arm round her?",
  "The journey continues.",
  "You’re about halfway home.",
  "Almost home.",
  "The taxi continues to your house.",
  "You get out.",
  "You find the key.",
  "You give her a kiss.",
  "You have the house to yourself.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "What will you do next?",
  "You move to the lounge.",
  "You think your brother has gone out with friends.",
]);

const thirdTail = [
  "Ask if she wants a pee?",
  "You put an arm round her.",
  "No, I’m happy as we are.",
  "She keeps looking at the door.",
  "She can’t sit still.",
  "She can’t sit still.",
  "Talk about stamps?",
  "You open the stamp album.",
  "She tucks one leg onto the sofa.",
  "You carry on.",
  "You put an arm round her and hug her to you.",
  "On with the stamps!",
  "You squeeze her hand.",
  "You move to a new album.",
  "You put an arm round her.",
  "You turn the pages.",
  "You hurry on with the album before she can interrupt.",
  "You carry on.",
  "You close the album.",
  "What next?",
  "She hurries from the room and up the stairs.",
  "You wait for her.",
  "Fondle her legs?",
  "She tries to break away.",
  "You wait for a reply.",
  "Hand in hand.",
];

const fourthTail = [
  "Kiss her?",
  "Yes, I’ll play a luckshot!",
  "You wait to see what happens.",
  "We shall see!",
  "Fondle her breasts?",
  "What next?",
  "You move your hand away and down to her bottom.",
  "What next?",
  "Walk her home and hope you have some fun on the way.",
  "Of course I’ll tell her. I’m a gentleman.",
  "You get ready to leave.",
  "I’ll be a gentleman and see her home.",
  "I’ll be a gentleman and see her home.",
  "You leave the house with her.",
  "You walk past a letterbox and then a bus shelter.",
  "You walk on.",
  "You walk on.",
  "She hurries you along.",
  "Think about it.",
  "Suggest she go behind the wall?",
  "You promise.",
  "You pretend to be looking away.",
  "And she can sense how excited you are.",
];

const firstTail = [
  "Kiss her?",
  "Yes, I’ll play a luckshot!",
  "You wait to see what happens.",
  "We shall see!",
  "Fondle her breasts?",
  "You go and sit on the sofa.",
  "You put an arm round her.",
  "You get ready to walk her home.",
  "No, I don’t think I’ll mention it.",
  "I’ll be a gentleman and see her home.",
  "I’ll be a gentleman and see her home.",
  "You leave the house with her.",
  "You walk past a letterbox and then a bus shelter.",
  "You try to keep up the conversation.",
  "You hurry to catch up.",
  "You watch in wonder.",
  "What are you going to do?",
  "Offer her a tissue?",
  "You give her a tissue.",
  "A couple of minutes later she rejoins you.",
  "Think about it.",
  "Tell her it’s turned you on?",
  "You stroke her hair.",
  "You walk on.",
  "You nod.",
];

const fifthTail = [
  "Kiss her?",
  "Yes, I’ll play a luckshot!",
  "You wait to see what happens.",
  "We shall see!",
  "Fondle her bottom?",
  "Explore her legs?",
  "Think about it.",
  "Take off her skirt?",
  "Triumph!",
  "You move towards her again.",
  "You go and sit by Diane.",
  "You pick up the skirt.",
  "Hold onto the skirt?",
  "You hold onto the skirt.",
  "You hold onto the skirt.",
  "Do a deal?",
  "You hand her the skirt",
  "And you follow.",
  "She puts the seat down.",
  "You watch in wonder.",
  "You embrace.",
  "How have you done?",
];

const secondSetup = [
  "Kiss her?",
  "You kiss again, your tongues touching.",
  "You put an arm round her.",
  "All’s well with the world.",
  "Explore her breasts?",
  "Yes, I’d like to unfasten her bra.",
  "You kiss.",
  "You kiss her.",
  "You run your hand down over her tummy.",
  "You caress her breasts again.",
  "Offer her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "You kiss again.",
  "Get her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Ask if she needs a pee?",
  "You like the sound of that.",
  "Maybe I’ll ask her to wait. But I’d better get more intimate first.",
];

const secondTail = [
  "Talk about something?",
  "Talk about toilets?",
  "You take her hand and pull her down onto your knee.",
  "You go to the kitchen.",
  "You drink your wine.",
  "You cuddle up.",
  "Yes, promise.",
  "You promise.",
  "Diane is holding on for dear life!",
  "You give her a cuddle.",
  "She shakes her head in bemusement.",
  "You give her a hug.",
  "She sits on the toilet.",
  "You wait.",
  "You breathe again.",
  "You go downstairs.",
  "Exactly.",
];

const loungeTail = [
  "Kiss her?",
  "You kiss again, your tongues touching.",
  "You put an arm round her.",
  "All’s well with the world.",
  "Explore her breasts?",
  "Yes, I’d like to unfasten her bra.",
  "You kiss.",
  "You kiss her.",
  "You run your hand down over her tummy.",
  "You caress her breasts again.",
  "Offer her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "You kiss again.",
  "Get her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "Ask if she needs a pee?",
  "You like the sound of that.",
  "Maybe I’ll ask her to wait. But I’d better get more intimate first.",
  "Talk about something?",
  "Talk about toilets?",
  "You take her hand and pull her down onto your knee.",
  "You go to the kitchen.",
  "You drink your wine.",
  "You cuddle up.",
  "Pull her onto your lap and ask her to tell you.",
  "Yes, promise.",
  "She pauses.",
  "You stroke her hair.",
  "She unzips your fly.",
  "She strokes you.",
  "You let her go.",
];

const generalRoute = common.concat([
  "Tuesday.",
  "On with the story!",
  "Buy something.",
  "An overpriced bottle of water (£3)",
  "Back to store.",
  "Just head for the theatre.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Talk about trains?",
  "Gosh!",
  "Carry on chatting.",
  "The waiter takes away your plates.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Panna cotta (£4 each)",
  "The sweets are quickly eaten.",
  "Just an ordinary filter coffee (£1 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Tell her you need to go too?",
  "She returns and you take your seats in the auditorium",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Just carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Ask her if she wants a pee?",
  "You go out onto the balcony.",
  "You carry on chatting",
  "Time to return to the play",
  "You go back to your seats.",
  "The second act begins.",
  "Lean closer to her?",
  "Carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Meet Molly at the stage door and maybe have a drink somewhere else?",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "What a good idea.",
  "You drink your coffees.",
  "She nestles closer to you.",
  "You are sitting next to Diane.",
  "You chat away.",
  "You all get up and continue your walk.",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "What are you going to talk about?",
  "Nothing in particular.",
  "OK.",
  "You hurry up.",
  "Hurrah!",
  "You walk on.",
  "You hurry along.",
  "You buy the drinks.",
  "Yes, I’ll play a luckshot.",
  "OK.",
  "She drinks her lager.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "Yes, I’ll buy another round of drinks.",
  "It’s your round, but quite a cheap one because of the special offers.",
  "Cheers!",
  "Good idea.",
  "Return to the beer garden.",
  "You drink up.",
  "No, there isn’t really time.",
  "You look for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Carry on waiting for the bus?",
  "What is it to be?",
  "You want to stay and watch the girl at the next bus stop, who looks desperate.",
  "You tell Diane you can’t think of anywhere.",
  "You carry on waiting.",
  "You hadn’t expected that.",
  "Yes, I do.",
  "Where did she go?",
  "Back towards the Pavilion? Maybe she’s hoping she’ll be able to get in to use the Ladies.",
  "I won’t be able to watch her in the club, so what’s the point.",
  "Will she go left?",
  "You hurry up those steps.",
  "You watch with bated breath.",
  "She looks around.",
  "Gosh!",
  "You head home.",
  "Nevertheless—",
]);

const generalThursdayBase = generalRoute
  .slice(0, generalRoute.indexOf("Back towards the Pavilion? Maybe she’s hoping she’ll be able to get in to use the Ladies."))
  .flatMap((label) => {
    if (label === "Tuesday.") return ["Thursday."];
    if (label === "Buy something.") return ["Just go there."];
    if (["An overpriced bottle of water (£3)", "Back to store.", "Just head for the theatre."].includes(label)) return [];
    if (label === "Which will it be?") return ["What will it be?"];
    if (label === "You drink up.") return ["And then it's time to leave."];
    if (label === "Yes, you’ve plenty of time.") return ["No, there isn’t really time."];
    return [label];
  });

const generalThursdayRawRoute = generalThursdayBase
  .slice(0, generalThursdayBase.indexOf("What are you going to talk about?"))
  .concat([
    "You carry on walking.",
    "You carry on walking.",
    "Walking and chatting.",
    "Chatting and walking.",
    "Hurrah!",
    "You walk on.",
    "You hurry along.",
  ])
  .concat(generalThursdayBase.slice(generalThursdayBase.indexOf("You buy the drinks.")))
  .concat([
    "Down the subway beneath the road, that will lead her back into town?",
    "Along the passage?",
    "You pause, then move forward slowly.",
    "But then you hear footsteps again.",
    "She doesn't move.",
    "Gosh!",
    "And before you can compose yourself—",
    "You haven't won, but at least—",
  ]);

let generalThursdayNeedsBusDueButton = false;
const generalThursdayRoute = generalThursdayRawRoute.flatMap((label) => {
  if (generalThursdayNeedsBusDueButton && label === "You carry on waiting.") {
    generalThursdayNeedsBusDueButton = false;
    return ["The bus is almost due."];
  }
  if (label === "You tell Diane you can’t think of anywhere.") {
    generalThursdayNeedsBusDueButton = true;
  }
  if (label === "You hadn’t expected that.") {
    return ["The bus finally comes into sight.", label];
  }
  return [label];
});

const chloeTail = [
  "She giggles nervously.",
  "The four of you chat.",
  "She giggles nervously again.",
  "What could it be?",
  "Gosh!",
  "She giggles nervously, then bites her lips, looking round the room.",
  "You feel a bit embarrassed for Chloe, who clearly doesn’t feel she can “spend a penny” while you’re all there. So you leave now with Diane, leaving Chloe and your brother alone.",
  "You leave with Diane.",
  "No, I don’t think I’ll mention it.",
  "I’ll be a gentleman and see her home.",
  "I’ll be a gentleman and see her home.",
  "You leave the house with her.",
  "You walk past a letterbox and then a bus shelter.",
  "You walk on.",
  "You walk on.",
  "She hurries you along.",
  "You turn for home.",
  "It just seems a shame it’s all over.",
  "You step into the shadows.",
  "Yes, I’ve got one left.",
  "Carry on.",
  "Duck out of sight.",
  "And then....",
  "Gosh!",
];

const amandaTail = [
  "Curses!",
  "You and Diane introduce yourselves.",
  "You help with the drinks.",
  "Gosh!",
  "No, I’ll fetch Diane’s book.",
  "You go towards your room.",
  "You don’t want to keep Diane waiting, and you’d like to see how Amanda is getting on. So you get the book.",
  "Go back into your room?",
  "You wait to see what happens.",
  "But you’ve got a grandstand view.",
  "Don’t you wish you could watch!",
  "Yes, why not!",
  "See what happens.",
  "Gosh!",
  "You carry on watching.",
  "It’s a date!",
  "—and so—",
];

const loungeHen = earlyBushHouseBase.concat(loungeTail);
const loungeTiramisu = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Tuesday.",
  "On with the story!",
  "Just go there.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Talk about trains?",
  "Gosh!",
  "Carry on chatting.",
  "The waiter takes away your plates.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Tiramisu (£5 each)",
  "The sweets are delicious and quickly eaten.",
  "Just an ordinary filter coffee (£1 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Try to stop her?",
  "You take your seats in the auditorium.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Just carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Tell her you need to go?",
  "You go out onto the balcony.",
  "You carry on chatting.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Lean closer to her?",
  "Carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Meet Molly at the stage door and maybe have a drink somewhere else?",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "What a good idea.",
  "You drink your coffees.",
  "She nestles closer to you.",
  "You are sitting next to Diane.",
  "You chat away.",
  "“You’re joking! I’m enjoying this.”",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "You’re quite happy about that.",
  "Talk about trains.",
  "She marches you forward.",
  "OK.",
  "How?",
  "Find her somewhere to go.",
  "She can’t stand still.",
  "Thank you, she says.",
  "You walk on.",
  "Hurrah!",
  "But you walk on past it.",
  "You hurry along.",
  "You buy the drinks.",
  "You go to the bar.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "Yes, I’ll buy another round of drinks.",
  "It’s your round, but quite a cheap one because of the special offers.",
  "Cheers!",
  "Good idea.",
  "Return to the beer garden.",
  "You drink up.",
  "You get ready to leave.",
  "And head for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Get the taxi?",
  "Find a taxi.",
  "You settle back.",
  "The taxi pulls away onto the main road.",
  "Put your arm round her?",
  "The journey continues.",
  "You’re about halfway home.",
  "Almost home.",
  "The taxi continues to your house.",
  "You get out.",
  "You find the key.",
  "You give her a kiss.",
  "They shake hands.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "He goes upstairs.",
  "What will you do next?",
  "So she says nothing.",
  "Kiss her?",
  "You kiss again, your tongues touching.",
  "You put an arm round her.",
  "All’s well with the world.",
  "Explore her breasts?",
  "No, I won’t unfasten her bra yet.",
  "You caress her breasts again.",
  "Offer her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "You kiss again.",
  "Get her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "Ask if she needs a pee?",
  "You like the sound of that.",
  "Maybe I’ll ask her to wait. But I’d better get more intimate first.",
  "Talk about something?",
  "Talk about toilets?",
  "You take her hand and pull her down onto your knee.",
  "You go to the kitchen.",
  "You drink your wine.",
  "You cuddle up.",
  "Pull her onto your lap and ask her to tell you.",
  "Yes, promise.",
  "She pauses.",
  "You stroke her hair.",
  "She unzips your fly.",
  "She strokes you.",
  "You let her go.",
];
const loungePanna = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Tuesday.",
  "On with the story!",
  "Buy something.",
  "An overpriced bottle of water (£3)",
  "Back to store.",
  "Just head for the theatre.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Talk about trains?",
  "Gosh!",
  "Carry on chatting.",
  "The waiter takes away your plates.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Panna cotta (£4 each)",
  "The sweets are quickly eaten.",
  "Just an ordinary filter coffee (£1 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Try to stop her?",
  "You take your seats in the auditorium.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Just carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Tell her you need to go?",
  "You go out onto the balcony.",
  "You carry on chatting.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Lean closer to her?",
  "Carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Meet Molly at the stage door and maybe have a drink somewhere else?",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "What a good idea.",
  "You drink your coffees.",
  "She nestles closer to you.",
  "You are sitting next to Diane.",
  "You chat away.",
  "“You’re joking! I’m enjoying this.”",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "You’re quite happy about that.",
  "Talk about trains.",
  "She marches you forward.",
  "OK.",
  "How?",
  "Find her somewhere to go.",
  "She can’t stand still.",
  "Thank you, she says.",
  "You walk on.",
  "Hurrah!",
  "But you walk on past it.",
  "You hurry along.",
  "You buy the drinks.",
  "You go to the bar.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "Yes, I’ll buy another round of drinks.",
  "It’s your round, but quite a cheap one because of the special offers.",
  "Cheers!",
  "Good idea.",
  "Return to the beer garden.",
  "You drink up.",
  "You get ready to leave.",
  "And head for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Get the taxi?",
  "Find a taxi.",
  "You settle back.",
  "The taxi pulls away onto the main road.",
  "Put your arm round her?",
  "The journey continues.",
  "You’re about halfway home.",
  "Almost home.",
  "The taxi continues to your house.",
  "You get out.",
  "You find the key.",
  "You give her a kiss.",
  "They shake hands.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "He goes upstairs.",
  "What will you do next?",
  "So she says nothing.",
  "Kiss her?",
  "You kiss again, your tongues touching.",
  "You put an arm round her.",
  "All’s well with the world.",
  "Explore her breasts?",
  "No, I won’t unfasten her bra yet.",
  "You caress her breasts again.",
  "Offer her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "You kiss again.",
  "Get her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "Ask if she needs a pee?",
  "You like the sound of that.",
  "Maybe I’ll ask her to wait. But I’d better get more intimate first.",
  "Talk about something?",
  "Talk about toilets?",
  "You take her hand and pull her down onto your knee.",
  "You go to the kitchen.",
  "You drink your wine.",
  "You cuddle up.",
  "Pull her onto your lap and ask her to tell you.",
  "Yes, promise.",
  "She pauses.",
  "You stroke her hair.",
  "She unzips your fly.",
  "She strokes you.",
  "You let her go.",
];
const loungeIce = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Tuesday.",
  "On with the story!",
  "Buy something.",
  "An overpriced bottle of water (£3)",
  "Back to store.",
  "Just head for the theatre.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Talk about trains?",
  "Gosh!",
  "Carry on chatting.",
  "The waiter takes away your plates.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Ice cream (£3 each)",
  "The ices are quickly eaten.",
  "Just an ordinary filter coffee (£1 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Try to stop her?",
  "You take your seats in the auditorium.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Just carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Tell her you need to go?",
  "You go out onto the balcony.",
  "You carry on chatting.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Lean closer to her?",
  "Carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Meet Molly at the stage door and maybe have a drink somewhere else?",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "What a good idea.",
  "You drink your coffees.",
  "She nestles closer to you.",
  "You are sitting next to Diane.",
  "You chat away.",
  "“You’re joking! I’m enjoying this.”",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "You’re quite happy about that.",
  "Talk about trains.",
  "She marches you forward.",
  "OK.",
  "How?",
  "Find her somewhere to go.",
  "She can’t stand still.",
  "Thank you, she says.",
  "You walk on.",
  "Hurrah!",
  "But you walk on past it.",
  "You hurry along.",
  "You buy the drinks.",
  "You go to the bar.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "Yes, I’ll buy another round of drinks.",
  "It’s your round, but quite a cheap one because of the special offers.",
  "Cheers!",
  "Good idea.",
  "Return to the beer garden.",
  "You drink up.",
  "You get ready to leave.",
  "And head for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Get the taxi?",
  "Find a taxi.",
  "You settle back.",
  "The taxi pulls away onto the main road.",
  "Put your arm round her?",
  "The journey continues.",
  "You’re about halfway home.",
  "Almost home.",
  "The taxi continues to your house.",
  "You get out.",
  "You find the key.",
  "You give her a kiss.",
  "They shake hands.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "He goes upstairs.",
  "What will you do next?",
  "So she says nothing.",
  "Kiss her?",
  "You kiss again, your tongues touching.",
  "You put an arm round her.",
  "All’s well with the world.",
  "Explore her breasts?",
  "No, I won’t unfasten her bra yet.",
  "You caress her breasts again.",
  "Offer her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "You kiss again.",
  "Get her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "Ask if she needs a pee?",
  "You like the sound of that.",
  "Maybe I’ll ask her to wait. But I’d better get more intimate first.",
  "Talk about something?",
  "Talk about toilets?",
  "You take her hand and pull her down onto your knee.",
  "You go to the kitchen.",
  "You drink your wine.",
  "You cuddle up.",
  "Pull her onto your lap and ask her to tell you.",
  "Yes, promise.",
  "She pauses.",
  "You stroke her hair.",
  "She unzips your fly.",
  "She strokes you.",
  "You let her go.",
];
const chloeSibling = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Tuesday.",
  "On with the story!",
  "Just go there.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Spaghetti bolognese (£8)",
  "Begin the meal.",
  "You chat about your meal.",
  "You concentrate on your eating.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Panna cotta (£4 each)",
  "The sweets are quickly eaten.",
  "Just an ordinary filter coffee (£1 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Or do you want to play the short version of the game?",
  "Yes, I’ll play the short version.",
  "Let’s see what happens!",
  "You find the key.",
  "You give her a kiss.",
  "It’s all very civilised.",
  "She giggles nervously.",
  "The four of you chat.",
  "She giggles nervously again.",
  "What could it be?",
  "Gosh!",
  "She giggles nervously, then bites her lips, looking round the room.",
  "You feel a bit embarrassed for Chloe, who clearly doesn’t feel she can “spend a penny” while you’re all there. So you leave now with Diane, leaving Chloe and your brother alone.",
  "You leave with Diane.",
  "No, I don’t think I’ll mention it.",
  "I’ll be a gentleman and see her home.",
  "I’ll be a gentleman and see her home.",
  "You leave the house with her.",
  "You walk past a letterbox and then a bus shelter.",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "You turn for home.",
  "It just seems a shame it’s all over.",
  "You step into the shadows.",
  "Yes, I’ve got one left.",
  "Carry on.",
  "Duck out of sight.",
  "And then....",
  "A nice end to the evening, but—",
];
const generalSaturday = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Saturday.",
  "On with the story!",
  "Buy something.",
  "An overpriced bottle of water (£3)",
  "Back to store.",
  "Just head for the theatre.",
  "Say you love the dress.",
  "OK.",
  "A bottle of Italian Pinot Grigio (£10)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Talk about trains?",
  "Gosh!",
  "Carry on chatting.",
  "The waiter takes away your plates.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Tiramisu (£5 each)",
  "The sweets are delicious and quickly eaten.",
  "An espresso (£1.50 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "You head into the theatre.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Not say anything?",
  "You drink your wine.",
  "You carry on chatting.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Hold her hand?",
  "Carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Meet Molly at the stage door and maybe have a drink somewhere else?",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "You say there really isn’t time.",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "What are you going to talk about?",
  "Nothing in particular.",
  "OK.",
  "You hurry up.",
  "Hurrah!",
  "You stop in your tracks.",
  "You walk on.",
  "You hurry along.",
  "You buy the drinks.",
  "Yes, I’ll play a luckshot.",
  "OK.",
  "She drinks her lager.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "Yes, I’ll buy another round of drinks.",
  "It’s your round, but quite a cheap one because of the special offers.",
  "Cheers!",
  "Good idea.",
  "Return to the beer garden.",
  "You drink up.",
  "Play a luckshot.",
  "Wait and see.",
  "You look for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Carry on waiting for the bus?",
  "What is it to be?",
  "You want to stay and watch the girl at the next bus stop, who looks desperate.",
  "You tell Diane you can’t think of anywhere.",
  "You carry on waiting.",
  "You hadn’t expected that.",
  "Yes, I do.",
  "Where did she go?",
  "Into the car park? There’s a public toilet on the other side, or maybe she’ll squat behind a car.",
  "What will she do?",
  "Gosh!",
  "Your date may have ended early, but it’s not been without its reward.",
];
const broochRoute = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Tuesday.",
  "On with the story!",
  "Buy something.",
  "A pretty little brooch (£15)",
  "Back to store.",
  "Just head for the theatre.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Ravioli—you’re trying to save money (£7)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Tiramisu (£5 each)",
  "The sweets are delicious and quickly eaten.",
  "Just an ordinary filter coffee (£1 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Or do you want to play the short version of the game?",
  "Yes, I’ll play the short version.",
  "Let’s see what happens!",
  "You find the key.",
  "You give her a kiss.",
  "You usher Diane in.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "What will you do next?",
  "You move to the lounge.",
  "What will you do next?",
  "So she says nothing.",
  "Ask if she wants a pee?",
  "You put an arm round her.",
  "No, I’m happy as we are.",
  "She keeps looking at the door.",
  "She can’t sit still.",
  "She can’t sit still.",
  "Talk about stamps?",
  "You open the stamp album.",
  "She tucks one leg onto the sofa.",
  "OK, I'll be kind.",
  "Choose this moment to give her the brooch.",
  "You get ready to walk her home.",
];
const phoneCallRoute = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Saturday.",
  "On with the story!",
  "Just go there.",
  "Say you love the dress.",
  "OK.",
  "A bottle of Italian Pinot Grigio (£10)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Talk about trains?",
  "Gosh!",
  "Carry on chatting.",
  "The waiter takes away your plates.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Tiramisu (£5 each)",
  "The sweets are delicious and quickly eaten.",
  "An espresso (£1.50 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "You head into the theatre.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Use a luckshot?",
  "You wait for her.",
  "You go out onto the balcony.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Hold her hand?",
  "Carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Be a gentleman and ask Diane what she wants to do.",
  "You head for the stagedoor.",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "You say there really isn’t time.",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "What are you going to talk about?",
  "Nothing in particular.",
  "OK.",
  "You hurry up.",
  "Hurrah!",
  "You stop in your tracks.",
  "You walk on.",
  "You hurry along.",
  "You buy the drinks.",
  "No, I’ll hold onto my luckshots.",
  "You chat together.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "No, I’m running out of money.",
  "No, I can’t afford it.",
  "You drink up.",
  "You get ready to leave.",
  "And head for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Get the taxi?",
  "Find a taxi.",
  "You wait.",
  "You carry on waiting.",
  "You are at the front of the queue.",
  "The taxi pulls away onto the main road.",
  "Put your arm round her?",
  "The journey continues.",
  "You’re about halfway home.",
  "Almost home.",
  "The taxi continues to your house.",
  "You get out.",
  "You find the key.",
  "You give her a kiss.",
  "They shake hands.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "He goes upstairs.",
  "What will you do next?",
  "So she says nothing.",
  "Offer her another drink?",
  "You go to the kitchen.",
  "Cheers!",
  "You carry on exploring and talking.",
  "Get her another drink?",
  "You go to the kitchen.",
  "Cheers!",
  "You carry on exploring and talking.",
  "Get her another drink?",
  "You go to the kitchen.",
  "Cheers!",
  "You carry on exploring and talking.",
  "Get her another drink?",
  "You go to the kitchen.",
  "Cheers!",
  "You carry on exploring and talking.",
  "Get her another drink?",
  "You go to the kitchen.",
  "Cheers!",
  "You carry on exploring and talking.",
  "Kiss her?",
  "Yes, I’ll play a luckshot!",
  "You wait to see what happens.",
  "We shall see!",
  "Fondle her breasts?",
  "What next?",
  "You move your hand away and down to her bottom.",
  "You go and sit on the sofa.",
  "You put an arm round her.",
  "She smiles up at you.",
  "Cheers!",
  "You carry on exploring and talking.",
  "Walk her home?",
  "No, I don’t think I’ll mention it.",
  "I’ll be a gentleman and see her home.",
  "I’ll be a gentleman and see her home.",
  "You leave the house with her.",
  "You walk past a letterbox and then a bus shelter.",
  "You walk on.",
  "You walk on.",
  "She hurries you along.",
  "Think about it.",
  "Say nothing? You’re enjoying it.",
  "Is that it?",
  "No, the poor girl’s desperate. I’m not going to spy on her.",
  "It’s a long time since you’ve seen a girlfriend so desperate for the loo.",
  "You step back into the shadows and watch.",
  "The show’s over.",
  "Yes.",
  "You don’t have enough intimacy points to pursue it further.",
];
const lootogetherRoute = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Tuesday.",
  "On with the story!",
  "Buy something.",
  "An overpriced bottle of water (£3)",
  "Back to store.",
  "Just head for the theatre.",
  "Say let’s go in and eat, then.",
  "A bottle of Spanish Rioja (£12)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Talk about trains?",
  "Gosh!",
  "Carry on chatting.",
  "The waiter takes away your plates.",
  "Cheers.",
  "No, let’s go straight to the coffees; the sweets are always a waste of money.",
  "An espresso (£1.50 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Try to stop her?",
  "You take your seats in the auditorium.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Just carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Tell her you need to go?",
  "You go out onto the balcony.",
  "You carry on chatting.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Lean closer to her?",
  "Carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Meet Molly at the stage door and maybe have a drink somewhere else?",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "What a good idea.",
  "You drink your coffees.",
  "She nestles closer to you.",
  "You are sitting next to Diane.",
  "You chat away.",
  "“You’re joking! I’m enjoying this.”",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "You’re quite happy about that.",
  "Talk about trains.",
  "She marches you forward.",
  "OK.",
  "How?",
  "Find her somewhere to go.",
  "She can’t stand still.",
  "Thank you, she says.",
  "You walk on.",
  "Hurrah!",
  "But you walk on past it.",
  "You hurry along.",
  "You buy the drinks.",
  "You go to the bar.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "Yes, I’ll buy another round of drinks.",
  "It’s your round, but quite a cheap one because of the special offers.",
  "Cheers!",
  "Good idea.",
  "Return to the beer garden.",
  "You drink up.",
  "You get ready to leave.",
  "And head for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Get the taxi?",
  "Find a taxi.",
  "You settle back.",
  "The taxi pulls away onto the main road.",
  "Put your arm round her?",
  "The journey continues.",
  "You’re about halfway home.",
  "Almost home.",
  "The taxi continues to your house.",
  "You get out.",
  "You find the key.",
  "You give her a kiss.",
  "They shake hands.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "He goes upstairs.",
  "What will you do next?",
  "So she says nothing.",
  "Kiss her?",
  "You kiss again, your tongues touching.",
  "You put an arm round her.",
  "All’s well with the world.",
  "Explore her breasts?",
  "No, I won’t unfasten her bra yet.",
  "You caress her breasts again.",
  "Offer her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "You kiss again.",
  "Get her another drink?",
  "You put your arm round her.",
  "To explore?",
  "She leans closer to you.",
  "Explore her legs?",
  "You kiss again.",
  "Ask if she needs a pee?",
  "You like the sound of that.",
  "Maybe I’ll ask her to wait. But I’d better get more intimate first.",
  "Talk about something?",
  "Talk about toilets?",
  "You take her hand and pull her down onto your knee.",
  "You go to the kitchen.",
  "You drink your wine.",
  "You cuddle up.",
  "Yes, promise.",
  "You promise.",
  "Diane is holding on for dear life!",
  "You give her a cuddle.",
  "She shakes her head in bemusement.",
  "You follow closely behind her.",
  "She goes over to the toilet.",
  "—and then—",
  "You watch in wonder.",
  "She flushes the toilet.",
  "But—",
  "You'd like to have seen her stream!",
];
const sofatrainsRoute = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Tuesday.",
  "On with the story!",
  "Just go there.",
  "Say let’s go in and eat, then.",
  "A bottle of Austrian Riesling (£12)",
  "Go on to the food menu.",
  "Ravioli—you’re trying to save money (£7)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "You carry on chatting.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Tiramisu (£5 each)",
  "The sweets are delicious and quickly eaten.",
  "An espresso (£1.50 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "Think about it.",
  "Or do you want to play the short version of the game?",
  "Yes, I’ll play the short version.",
  "Let’s see what happens!",
  "You find the key.",
  "You give her a kiss.",
  "You usher Diane in.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "What will you do next?",
  "You move to the lounge.",
  "What will you do next?",
  "So she says nothing.",
  "Ask if she wants a pee?",
  "You put an arm round her.",
  "No, I'm happy as we are.",
  "She keeps looking at the door.",
  "She can't sit still.",
  "She can't sit still.",
  "Talk about trains?",
  "You open the photo album.",
  "You turn the pages.",
  "You carry on.",
  "You turn the pages.",
  "On with the trains!",
  "You stroke her hair.",
  "You move to a new album.",
  "You carry on with the book.",
  "You turn the pages.",
  "You give her a kiss.",
  "You carry on.",
  "You tell her there are just a couple more pages.",
  "Almost finished!",
];
const bathpeeRoute = [
  "I've already read them. I'll get straight on with the game.",
  "When can you see her?",
  "Saturday.",
  "On with the story!",
  "Buy something.",
  "An overpriced bottle of water (£3)",
  "Back to store.",
  "Just head for the theatre.",
  "Say you love the dress.",
  "OK.",
  "A bottle of Italian Pinot Grigio (£10)",
  "Go on to the food menu.",
  "Tortelloni, the same as Diane (£9)",
  "Begin the meal.",
  "You chat about your meal.",
  "You carry on eating.",
  "What will it be?",
  "Talk about trains?",
  "Gosh!",
  "Carry on chatting.",
  "The waiter takes away your plates.",
  "Cheers.",
  "Yes, let’s have a sweet.",
  "Panna cotta (£4 each)",
  "The sweets are quickly eaten.",
  "An espresso (£1.50 each)",
  "You carry on chatting.",
  "You leave the restaurant and head into the theatre.",
  "You head into the theatre.",
  "You watch the play.",
  "Thinking about the way you met?",
  "Concentrate on the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Carry on watching the play.",
  "Hold her hand?",
  "Carry on watching the play.",
  "Concentrate on the play.",
  "Concentrate on the play.",
  "You look at Diane.",
  "You chat about the play.",
  "Not say anything?",
  "You drink your wine.",
  "You carry on chatting.",
  "Time to return to the play.",
  "You go back to your seats.",
  "The second act begins.",
  "Hold her hand?",
  "Carry on watching the play.",
  "The actress really knows how to play desperation.",
  "You’re enjoying the play.",
  "The play continues.",
  "The lights dim.",
  "The play continues.",
  "The play has almost ended.",
  "You stand up to leave the theatre.",
  "In the meantime everyone is filing out of the auditorium.",
  "Meet Molly at the stage door and maybe have a drink somewhere else?",
  "—and head towards the stage door.",
  "You wait for Molly.",
  "You wait for Molly.",
  "You shake hands with Molly and her friend.",
  "Which will it be?",
  "Go for the walk.",
  "You walk on.",
  "You reach the river.",
  "What a good idea.",
  "You drink your coffees.",
  "She nestles closer to you.",
  "You are sitting next to Diane.",
  "You chat away.",
  "“You’re joking! I’m enjoying this.”",
  "You walk on.",
  "You walk on.",
  "You walk on.",
  "You’re quite happy about that.",
  "Nothing in particular.",
  "OK.",
  "How?",
  "Tell her you need to go as well.",
  "Go behind the bushes?",
  "That's better, she says.",
  "You walk on.",
  "Hurrah!",
  "But you walk on past it.",
  "You hurry along.",
  "You buy the drinks.",
  "You go to the bar.",
  "You chat away.",
  "You chat away.",
  "You chat on.",
  "Yes, I’ll buy another round of drinks.",
  "It’s your round, but quite a cheap one because of the special offers.",
  "Cheers!",
  "Good idea.",
  "Return to the beer garden.",
  "You drink up.",
  "You get ready to leave.",
  "And head for the bus stop.",
  "You carry on waiting.",
  "Think about it.",
  "Get the taxi?",
  "Find a taxi.",
  "You wait.",
  "You carry on waiting.",
  "You are at the front of the queue.",
  "The taxi pulls away onto the main road.",
  "Put your arm round her?",
  "The journey continues.",
  "You’re about halfway home.",
  "Almost home.",
  "The taxi continues to your house.",
  "You get out.",
  "You find the key.",
  "You give her a kiss.",
  "They shake hands.",
  "A small mug of real filter coffee?",
  "You drink the coffee.",
  "He goes upstairs.",
  "What will you do next?",
  "So she says nothing.",
  "Put an arm round her?",
  "No, I’m happy as we are.",
  "To explore?",
  "She leans closer to you.",
  "Explore her breasts?",
  "Yes, I’d like to unfasten her bra.",
  "You kiss.",
  "You kiss her.",
  "You run your hand down over her tummy.",
  "You caress her breasts again.",
  "Time for decisions on your part.",
  "Talk about something?",
  "Talk about toilets?",
  "You take her hand and pull her down onto your knee.",
  "You go to the kitchen.",
  "You drink your wine.",
  "You cuddle up.",
  "Yes, promise.",
  "You promise.",
  "Diane is holding on for dear life!",
  "You give her a cuddle.",
  "She shakes her head in bemusement.",
  "You give her a hug.",
  "You watch.",
  "You wait.",
  "You go downstairs.",
  "Exactly.",
];


// Official prize endings (must end on a detected prize line — used by guide capture).
const routes = {
  third: tuesdayShortHouse.concat(thirdTail),
  fourth: saturdayHouse.concat(firstDrink, flatRepeat(repeatDrink, 4), fourthTail),
  first: saturdayHouse.concat(firstDrink, flatRepeat(repeatDrink, 10), firstTail),
  fifth: thursdayFifthBase.concat(fifthTail),
  second: earlyBushHouseBase.concat(secondSetup, secondTail),
  lounge: loungeHen,
  loungeHen,
  loungeTiramisu,
  loungePanna,
  loungeIce,
  general: generalRoute,
  generalThursday: generalThursdayRoute,
  generalSaturday,
  chloe: chloeBase.concat(chloeTail),
  amanda: amandaBase.concat(amandaTail),
};

// Full set for Gallery (includes game-over / mid-route hidden scenes).
const galleryRoutes = Object.assign({}, routes, {
  chloeSibling,
  brooch: broochRoute,
  phoneCall: phoneCallRoute,
  lootogether: lootogetherRoute,
  sofatrains: sofatrainsRoute,
  bathpee: bathpeeRoute,
});

function flatRepeat(route, count) {
  return Array.from({ length: count }, () => route).flat();
}

function stripTags(text) {
  return String(text)
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/\u202f/g, "\uE000")
    .replace(/\s+/g, " ")
    .replace(/\uE000/g, "\u202f")
    .trim();
}

function normalize(text) {
  // Guides may use “…” / "…" while polishChoiceText renders British ‘…’.
  // Strip all quote marks after folding curly→straight so inner quotes match too
  // (e.g. "spend a penny" vs ‘spend a penny’).
  return stripTags(text)
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/["']/g, "")
    .replace(/\s*[—–]\s*/g, "-")
    .replace(/\s+/g, " ")
    .trim();
}

function loadGame(htmlPath) {
  const source = fs.readFileSync(htmlPath, "utf8");
  const script = source.match(/<script>([\s\S]*?)<\/script>/i)[1];
  const initialBox = (source.match(/<div id="box"[^>]*>([\s\S]*?)<\/div>\s*<\/div>\s*<\/body>/i) || [null, ""])[1]
    .replace(/^\s+|\s+$/g, "");
  const box = { innerHTML: initialBox };
  const context = {
    console,
    document: {
      getElementById(id) {
        if (id !== "box") throw new Error(`unknown element ${id}`);
        return box;
      },
    },
  };
  context.window = context;
  vm.createContext(context);
  vm.runInContext(script, context, { filename: htmlPath });
  return { context, box };
}

function choices(game) {
  const out = [];
  const re = /<button class=['"]choice['"] onclick=(?:"go\('([^']+)'\)"|'go\("([^"]+)"\)')>([\s\S]*?)<\/button>/g;
  let match;
  while ((match = re.exec(game.box.innerHTML))) {
    out.push({ tag: match[1] || match[2], text: stripTags(match[3]) });
  }
  return out;
}

function visibleText(game) {
  return stripTags(game.box.innerHTML);
}

function findChoice(options, label) {
  const wanted = normalize(label);
  let found = options.find((o) => normalize(o.text) === wanted);
  if (!found) {
    found = options.find(
      (o) => normalize(o.text).replace(/[.!?。！？]+$/u, "") === wanted.replace(/[.!?。！？]+$/u, ""),
    );
  }
  return found;
}

function captureLabelsAndTags(htmlPath, route) {
  const game = loadGame(htmlPath);
  const labels = [];
  const tags = [];
  for (const label of route) {
    const options = choices(game);
    const found = findChoice(options, label);
    if (!found) {
      throw new Error(
        `Choice not found in ${htmlPath}: ${label}\nAvailable:\n${options.map((o) => `- ${o.text}`).join("\n")}\n\nPage:\n${visibleText(game).slice(0, 1200)}`,
      );
    }
    labels.push(found.text);
    tags.push(found.tag);
    game.context.go(found.tag);
  }
  return { labels, tags, text: visibleText(game), vars: vars(game) };
}

function captureLabelsByTags(htmlPath, tags) {
  const game = loadGame(htmlPath);
  const labels = [];
  for (const tag of tags) {
    const options = choices(game);
    const found = options.find((o) => o.tag === tag);
    if (!found) {
      throw new Error(
        `Tag not found in ${htmlPath}: ${tag}\nAvailable:\n${options.map((o) => `- ${o.tag}: ${o.text}`).join("\n")}\n\nPage:\n${visibleText(game).slice(0, 1200)}`,
      );
    }
    labels.push(found.text);
    game.context.go(found.tag);
  }
  return { labels, text: visibleText(game), vars: vars(game) };
}

function vars(game) {
  return Object.fromEntries(game.context.gameStateVars.map((k) => [k, game.context[k]]));
}

function ending(text, lang) {
  const byLang = {
    en: [
      /TRULY, YOU HAVE WON FIRST PRIZE!/,
      /YOU HAVE WON A CONSOLATION PRIZE!/,
      /YOU HAVE WON [^!]+!/,
      /WHICH IS A PRETTY GOOD CONSOLATION PRIZE!/,
    ],
    cn: [
      /你真的(?:获得|赢得)了一等奖！/,
      /你(?:获得|赢得)了[一二三四五]等奖！/,
      /你(?:获得|赢得)了(?:一个)?安慰奖！/,
      /这倒也算个相当不错的安慰奖！/,
    ],
    tw: [
      /你真的獲得了一等獎！/,
      /你獲得了[一二三四五]等獎！/,
      /你獲得了(?:一個)?安慰獎！/,
      /這倒也算個相當不錯的安慰獎！/,
    ],
    es: [
      /¡(?:VERDADERAMENTE, |DE VERDAD )HAS GANADO EL PRIMER PREMIO!/,
      /¡HAS GANADO UN PREMIO DE CONSOLACIÓN!/,
      /¡HAS GANADO EL \d\.(?:er|º) PREMIO!/,
      /¡QUE NO ES MAL PREMIO DE CONSOLACIÓN!/,
    ],
    fr: [
      /VRAIMENT, VOUS AVEZ REMPORTÉ LE PREMIER PRIX[\s\u202F]*!/,
      /VOUS AVEZ REMPORTÉ UN (?:PRIX|LOT) DE CONSOLATION[\s\u202F]*!/,
      /VOUS AVEZ (?:REMPORTÉ|GAGNÉ) LE \dE PRIX[\s\u202F]*!/,
      /CE QUI EST UN SACRÉ LOT DE CONSOLATION[\s\u202F]*!/,
    ],
  };
  const patterns = byLang[lang] || byLang.en;
  for (const pattern of patterns) {
    const match = text.match(pattern);
    if (match) return match[0];
  }
  return "NO ENDING TEXT FOUND";
}

// --- route smoke test (script entry; gallery/hidden loaders cut above this line) ---
LEGACY_GUIDE_OUTPUTS.forEach((target) => {
  fs.rmSync(target, { recursive: true, force: true });
});

for (const [key, route] of Object.entries(routes)) {
  const en = captureLabelsAndTags(EN_HTML, route);
  const cn = captureLabelsByTags(CN_HTML, en.tags);
  const es = captureLabelsByTags(ES_HTML, en.tags);
  const fr = captureLabelsByTags(FR_HTML, en.tags);
  const tw = captureLabelsByTags(TW_HTML, en.tags);
  console.log(`OK ${key}: EN="${ending(en.text, "en")}" CN="${ending(cn.text, "cn")}" ES="${ending(es.text, "es")}" FR="${ending(fr.text, "fr")}" TW="${ending(tw.text, "tw")}"`);
}

console.log(`Verified ${Object.keys(routes).length} ending routes across en/cn/tw/es/fr (no guide files written).`);
